[project]
name = "moviedb-graphql-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "sqlalchemy>=2.0",
    "strawberry-graphql[fastapi]>=0.320.1",
    "strawberry-sqlalchemy-mapper>=0.8.0",
    "uvicorn[standard]>=0.34.0",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pylint>=4.0.6",
    "pytest>=9.1.1",
]
